feat(APP-3714): Modify repo for ODS to GovKit transition
aragon/gov-ui-kit pull request #313
Opened 2024-10-18 12:24 UTC by thekidnamedkd

## Description

Replace all docs, tokens, strings, component names, etc.

Task: [APP-3714](https://aragonassociation.atlassian.net/browse/APP-3714)

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

## Checklist:

-   [x] I have selected the correct base branch.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] I have made corresponding changes to the documentation.
-   [x] My changes generate no new warnings.
-   [x] Any dependent changes have been merged and published in downstream modules.
-   [x] I ran all tests with success and extended them if necessary.
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before
        the latest version.
-   [x] I have tested my code on the test network.

2024-10-22 07:26 UTC, shan8851 requested changes
Looks good, I can see some references still in `gukModulesProvider.tsx`

```tsx
const odsModulesContextDefaults: IGukModulesContext = {
    copy: modulesCopy,
};

const odsModulesContext = createContext<IGukModulesContext>(odsModulesContextDefaults);

export const GukModulesProvider: React.FC<IGukModulesProviderProps> = (props) => {
    const {
        queryClient = defaultQueryClient,
        wagmiConfig = defaultWagmiConfig,
        wagmiInitialState,
        coreProviderValues,
        children,
        values,
    } = props;

    const contextValues = useMemo(
        () => ({
            copy: values?.copy ?? odsModulesContextDefaults.copy,
        }),
        [values],
    );

    return (
        <odsModulesContext.Provider value={contextValues}>
            <WagmiProvider config={wagmiConfig} initialState={wagmiInitialState}>
                <QueryClientProvider client={queryClient}>
                    <GukCoreProvider values={coreProviderValues}>{children}</GukCoreProvider>
                </QueryClientProvider>
            </WagmiProvider>
        </odsModulesContext.Provider>
    );
};

export const useGukModulesContext = (): IGukModulesContext => {
    const values = useContext(odsModulesContext);

    return values;
};
```

2024-10-22 14:52 UTC, cgero-eth commented on CHANGELOG.md
> +-   Implement `GukCoreProvider`, `LinkBase` and `AvatarBase` core components to support `Link` and `Image` NextJs
I would keep these names here, on previous versions the component will still be called `OdsXYZ`. Instead we can add a new entry under `unreleased` as `Rename x component to y`.
Let's specify on the changelog that we're renaming these components and the css custom variables

2024-10-22 14:52 UTC, cgero-eth commented on README.md
> +The Aragon Governance UI Kit is released under the AGPL v3 License.
The link to the LICENSE file is now missing

2024-10-22 14:52 UTC, cgero-eth commented on README.md
> +Stuck on something? Our community is here to help! Join our [Discord channel](https://discord.com/invite/eqQJkdp) for
No discord links, these can get outdated

2024-10-22 14:53 UTC, cgero-eth commented on src/theme/tokens/index.mdx
> +The design tokens in the `@aragon/guk` UI library serve as the foundational elements for creating consistent and
gov-ui-kit

2024-10-22 14:55 UTC, cgero-eth commented on src/theme/tokens/index.mdx
> +In projects using both `@aragon/guk` and `Tailwind CSS`, design tokens are readily available as Tailwind classes. For
gov-ui-kit
also below

2024-10-22 14:55 UTC, cgero-eth commented on src/modules/index.mdx
> +    import { GukModulesProvider } from '@aragon/guk';
gov-ui-kit

2024-10-22 14:58 UTC, cgero-eth commented on src/core/utils/formatterUtils/formatterUtils.mdx
> +import { NumberFormat, formatterUtils } from '@aragon/guk';
gov-ui-kit
Same below

2024-10-23 08:11 UTC, cgero-eth commented on CHANGELOG.md
> +-   Update `GukModulesProvider` component to render the `GukCoreProvider` context.
```suggestion
-   Update `OdsModulesProvider` component to render the `OdsCoreProvider` context.
```

2024-10-23 08:11 UTC, cgero-eth commented on CHANGELOG.md
> +-   Implement `GukModulesProvider` for using wagmi hooks on modules components
```suggestion
-   Implement `OdsModulesProvider` for using wagmi hooks on modules components
```

2024-10-23 08:11 UTC, cgero-eth commented on README.md
> +The Aragon Governance UI Kit is released under the [GPL-V3](./LICENSE).
```suggestion
The Aragon Governance UI Kit is released under the [GPL-V3 License](./LICENSE).
```

2024-10-23 08:25 UTC, cgero-eth approved these changes
LGTM, thanks @thekidnamedkd! 🚀

2024-10-23 08:25 UTC, merged